#!/bin/sh
#
# Hotplug script for WWAN module configuration on HAT OPIZ
# Function: Auto-configure USB path that changes on boot
#
# Support: EM7430, EM7455, LT4220, L850-GL, L860-GL, 
#          DW5821e, T99W175, FM350-GL, RM50XX
# Credit : MBAH WISNU
# @lionware <lionware@siltesa.com>
# February 2025
#

# Check device is OrangePi Zero3
if ! grep -q "OrangePi Zero3" /proc/device-tree/model 2>/dev/null; then
    logger -t usb_wwan_hat "Not OrangePi Zero3, exit..."
    exit 0
fi

# Debug (uncomment if needed)
#logger -t usb_debug "ACTION: $ACTION, PRODUCT: $PRODUCT"

# Check action and module VID
if [[ "$ACTION" == "add" || "$ACTION" == "change" || "$ACTION" == "remove" ]] && \
   [[ "$(echo $PRODUCT | cut -d'/' -f1)" == "2cb7" || \
      "$(echo $PRODUCT | cut -d'/' -f1)" == "1199" || \
      "$(echo $PRODUCT | cut -d'/' -f1)" == "8087" || \
      "$(echo $PRODUCT | cut -d'/' -f1)" == "413c" || \
      "$(echo $PRODUCT | cut -d'/' -f1)" == "1bc7" || \
      "$(echo $PRODUCT | cut -d'/' -f1)" == "2c7c" || \
      "$(echo $PRODUCT | cut -d'/' -f1)" == "3f0" || \
      "$(echo $PRODUCT | cut -d'/' -f1)" == "489" || \
      "$(echo $PRODUCT | cut -d'/' -f1)" == "5c6" || \
      "$(echo $PRODUCT | cut -d'/' -f1)" == "e8d" ]]; then
      
   # Get interface names
   mm_modemIface=$(uci show network | grep "proto='modemmanager'" | awk -F '.' '{print $2}')
   atc_modemIface=$(uci show network | grep "proto='atc'" | awk -F '.' '{print $2}')
   xmm_modemIface=$(uci show network | grep "proto='xmm'" | awk -F '.' '{print $2}')
   
    # Set serial port
    set_port_serial(){
        uci set 3ginfo.@3ginfo[0].device="$1"
        uci set atcommands.@atcommands[0].set_port="$1"
        uci set modemband.@modemband[0].set_port="$1"
        uci set modeminfo.@modeminfo[0].device="$1"
        uci set sms_tool_js.@sms_tool_js[0].readport="$1"
        uci set sms_tool_js.@sms_tool_js[0].sendport="$1"
        uci set sms_tool_js.@sms_tool_js[0].ussdport="$1"
        uci set sms_tool_js.@sms_tool_js[0].atport="$1"
        uci -q commit 3ginfo
        uci -q commit atcommands
        uci -q commit modemband.@modemband[0]
        uci -q commit modeminfo
        uci -q commit sms_tool_js
    }
    
    # Set LED HAT
    set_led_hat(){ 
        uci set system.@led[0].dev="$1"
        uci -q commit system
        service led restart
    }
    
    # Enable proto ATC only
    set_proto_atc(){
        uci set network.atc.disabled="0"
        uci set network.mm.disabled="1"
        uci set network.xmm.disabled="1"
        uci -q commit network
                
        if [[ "$(ifstatus $atc_modemIface | grep '"up":' | awk -F': ' '{print $2}' | tr -d ',')" == "false" ]]; then
          logger -t usb_wwan_hat "Bring up interface $atc_modemIface"
          ifdown $atc_modemIface
          sleep 1
          ifup $atc_modemIface
        fi
    }
    
    # Enable proto MM only
    set_proto_mm(){
        uci set network.atc.disabled="1"
        uci set network.mm.disabled="0"
        uci set network.xmm.disabled="1"
        uci -q commit network
        
        if [[ "$(ifstatus $mm_modemIface | grep '"up":' | awk -F': ' '{print $2}' | tr -d ',')" == "false" ]]; then
          logger -t usb_wwan_hat "Bring up interface $mm_modemIface"
          ifup $mm_modemIface
        fi
    }
    
    # Enable proto XMM only
    set_proto_xmm(){
        uci set network.atc.disabled="1"
        uci set network.mm.disabled="1"
        uci set network.xmm.disabled="0"
        uci -q commit network
                
        if [[ "$(ifstatus $xmm_modemIface | grep '"up":' | awk -F': ' '{print $2}' | tr -d ',')" == "false" ]]; then
          logger -t usb_wwan_hat "Bring up interface $xmm_modemIface"
          ifup $xmm_modemIface
        fi
    }
    
    # Setup based on VID
    setup_wwan(){
        VID="$1"
    
        case "$VID" in
            "1199") # EM7430 / EM7455
                set_port_serial "/dev/ttyUSB1"
                set_led_hat "wwan0"
                sed -i 's/^# \(mm_log "info" .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^# \(mm_report_event .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_mm
                ;;
            "2c7c") # RM5XX Series
                set_port_serial "/dev/ttyUSB2"
                set_led_hat "wwan0"
                sed -i 's/^# \(mm_log "info" .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^# \(mm_report_event .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_mm
                ;;
            "3f0")  # LT4220
                set_port_serial "/dev/ttyUSB2"
                set_led_hat "wwan0"
                sed -i 's/^# \(mm_log "info" .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^# \(mm_report_event .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_mm
                ;;
            "2cb7") # L850
                set_port_serial "/dev/ttyACM0"
                set_led_hat "wwan0"
                sed -i 's/^# \(mm_log "info" .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^# \(mm_report_event .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_mm
                ;;
            "8087") # L860
                set_port_serial "/dev/ttyACM0"
                set_led_hat "eth1"
                sed -i 's/^# \(mm_log "info" .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^# \(mm_report_event .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_xmm
                ;;
            "413c") # DW5821e
                set_port_serial "/dev/ttyUSB0"
                set_led_hat "wwan0"
                sed -i 's/^# \(mm_log "info" .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^# \(mm_report_event .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_mm
                ;;
            "1bc7") # LN940
                set_port_serial "/dev/ttyUSB0"
                set_led_hat "wwan0"
                sed -i 's/^# \(mm_log "info" .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^# \(mm_report_event .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_mm
                ;;
            "489")  # Foxconn
                set_port_serial "/dev/ttyUSB0"
                set_led_hat "wwan0"
                sed -i 's/^# \(mm_log "info" .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^# \(mm_report_event .*\)/\1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_mm
                ;;
            "5c6")  # T99W175
                set_port_serial "/dev/ttyUSB3"
                set_led_hat "wwan0"
                # Disable MM log (fix loop)
                sed -i 's/^\(mm_log "info" .*\)/# \1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^\(mm_report_event .*\)/# \1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_mm
                ;;
            "e8d")  # FM350-GL
                set_port_serial "/dev/ttyUSB4"
                set_led_hat "eth1"
                # Disable MM log
                sed -i 's/^\(mm_log "info" .*\)/# \1/' /etc/hotplug.d/tty/25-modemmanager-tty
                sed -i 's/^\(mm_report_event .*\)/# \1/' /etc/hotplug.d/tty/25-modemmanager-tty
                set_proto_atc
                ;;
            *)
                logger -t usb_wwan_hat "Unknown VID"
                ;;
        esac
    }      
      
    # Run if status file doesn't exist
    if [[ ! -f /tmp/wwan_modem_hat.status ]]; then
        vid_wwan="$(echo $PRODUCT | cut -d'/' -f1)"
        device_path="/sys${DEVPATH}"

        if [ -n "$device_path" ]; then
            logger -t usb_wwan_hat "Start device configuration"
            logger -t usb_wwan_hat "ACTION: $ACTION, PRODUCT: $PRODUCT"
            logger -t usb_wwan_hat "Path: ${device_path}"
            
            # Update USB path
            uci set network."$mm_modemIface".device="$device_path"
            
            # Setup modem
            setup_wwan $vid_wwan
            
            # Save status
            logger -t usb_wwan_hat "Configuration completed"
            echo "$vid_wwan" > /tmp/wwan_modem_hat.status
        fi
    fi
    
    # Remove status on device removal
    if [[ -f /tmp/wwan_modem_hat.status && "$ACTION" == "remove" ]]; then
        logger -t usb_wwan_hat "Remove status"
        rm -f /tmp/wwan_modem_hat.status
    fi
fi
