#!/bin/sh
#
# Hotplug script for Wi-Fi module configuration on HAT OPIZ
# Auto-configure USB path on OpenWrt when device boots or restarts
#
# Support Device:
#  * RTL8188CUS
#  * RTL8188EUS
#  * RTL8192EU
#  * RTL8192FU
#
# @lionware <lionware@siltesa.com>
# Februari 2025
# Credit Mbah Wisnu 
# Distribusi dan penggunaan kode ini diperbolehkan digunakan di perangkat manapun dan dapat dimodifikasi, 
# tetapi tanpa jaminan kode ini berjalan dengan baik di perangkat tersebut :v
#
# Wi-Fi HAT (USB Wi-Fi)
#
# Debug USB
logger -t usb_debug_wlan "ACTION: $ACTION, PRODUCT: $PRODUCT"

# Check OrangePi Zero3 device only
if ! grep -q "OrangePi Zero3" /proc/device-tree/model 2>/dev/null; then
    logger -t usb_wifi_hat "Not OrangePi Zero3, exiting"
    exit 0
fi

# Check USB Wi-Fi device detection
if [[ "$ACTION" == "add" || "$ACTION" == "bind" ]] && \
   [[ "$(echo $PRODUCT | cut -d'/' -f1)" == "bda" || "$(echo $PRODUCT | cut -d'/' -f1)" == "2357" ]] && \
   [[ "$(echo $PRODUCT | cut -d'/' -f2)" == "8179" || \
      "$(echo $PRODUCT | cut -d'/' -f2)" == "8178" || \
      "$(echo $PRODUCT | cut -d'/' -f2)" == "8176" || \
      "$(echo $PRODUCT | cut -d'/' -f2)" == "818b" || \
      "$(echo $PRODUCT | cut -d'/' -f2)" == "010c" ]]; then
      # Note: Remove leading zero from VID
      # Example: 0bda becomes bda
      # VID = -f1, PID = -f2

    # Get USB device path
    device_path_wifi="${DEVPATH#/devices/}"
    
    # Configure if path found
    if [[ -n "$device_path_wifi" ]]; then
        # Log configuration start
        logger -t usb_wifi_hat "Device matched, configuring"
        logger -t usb_wifi_hat "ACTION: $ACTION, PRODUCT: $PRODUCT"
                
        # Remove radio2 if exists
        if uci show wireless.radio2 &>/dev/null; then
            wifi down radio2
            logger -t usb_wifi_hat "Deleting radio2"
            uci -q delete wireless.radio2
            uci -q delete wireless.default_radio2
        fi
        
        # Update Wi-Fi configuration
        uci set wireless.radio1.path="$device_path_wifi"
        uci set wireless.default_radio1.ieee80211w="2"
        uci -q commit wireless
        wifi up radio1
        
        # Check radio1 status
        status_radio1=$(wifi status | awk '/"radio1":/ {flag=1} flag && /"up":/ {gsub(",", "", $2); print $2; flag=0}')
        
        # Activate if status is false
        if [[ "$status_radio1" == false ]]; then
            logger -t usb_wifi_hat "Activating wireless HAT"
            wifi up radio1
            echo "OK" > /tmp/wifi_up.status
        fi
    fi
fi
